### ISSUE TITLE
可以教教我怎么使用吗？

### ISSUE THREAD

**Issue by jinshuqishi2019** [xdb23/jinli#1]
你好，请教下怎么使用，谢谢

**Comment by xdb23** [comment]
这个是前段时间免费的时候建的库，现在收费了，可以不用拉

**Comment by jinshuqishi2019** [comment]
麻烦了，收费的库的链接吗？有这方面的需求，谢谢。

**Comment by xdb23** [comment]
你是要跑锦鲤吗，tg有的，推荐BBK，他也有拉库链接
支持锦鲤红包(mck、appck)、挖宝助力的机器人，点击链接快来试试吧！
https://t.me/TBodyBot?start=2c0df67532400c1c41efa0e5ad41678f

**Comment by jinshuqishi2019** [comment]
非常感谢你的解答，请问还有用点点券抢59-20的频道或者群吗？
